In [7]:
planetas = ["Mercurio", "Venus", "Tierra", "Marte", "Jupiter", "Saturno", "Urano", "Neptuno"]
planetas

['Mercurio',
 'Venus',
 'Tierra',
 'Marte',
 'Jupiter',
 'Saturno',
 'Urano',
 'Neptuno']

2. Haz que Python te diga cuántos planetas hay examinando tu lista

In [9]:
len(planetas)

8

3. Muestre los primeros cuatro planetas del sistema solar (los planetas rocosos)

In [13]:
print("Planetas Rocosos:", planetas[0:4])

Planetas Rocosos: ['Mercurio', 'Venus', 'Tierra', 'Marte']


4.Imprimir el nombre del planeta que tiene una s al final de su nombre

In [14]:
print(planetas[1])

Venus


In [2]:
T = 30.3

In [3]:
C = (5/9)*(T-32)
C

-0.9444444444444441

In [5]:
print ("Grados Farenheit:", T,
       "Grados Celsius:", C)

Grados Farenheit: 30.3 Grados Celsius: -0.9444444444444441


In [8]:
import numpy as np

array = np.array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [10]:
reshape = np.reshape(array, (4,4))
reshape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [19]:
grados = np.array([0,30,45,60,90])

con_Rad = np.pi/180 #Factor Conversion a radianes

Radianes = grados*con_Rad
Radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [35]:
seno = np.sin(Radianes)
seno

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [37]:
coseno = np.cos(Radianes)
coseno

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])